spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_POST:27017}
      database: ${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      authentication-database: admin

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8000