apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-crud
  template:
    metadata:
      labels:
        app: user-crud
    spec:
      containers:
        - name: user-crud
          image: alariclightin/user-crud:1.0
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-crud-config
                  key: MONGO_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-crud-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-crud-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-crud-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000