replicaCount: 2

image:
  repository: alariclightin/user-crud
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

mongodb:
  nameOverride: mongodb
  auth:
    rootUser: mongoadmin
    rootPassword: rootPassword
    # почему-то без этого поля Хелм не работает
    password: password

mongodb_custom:
  default_database: simple_crud