{
 "title": "User CRUD Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "API Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency - Get users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "max(histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval]))))",
     "legendFormat": "p99"
    },
    {
     "expr": "max(histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval]))))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency - Get single user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency - Add user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\", uri=\"/users\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency - Delete user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"DELETE\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency - Edit user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PATCH\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PATCH\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PATCH\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PATCH\", uri=\"/users/{id}\", status!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "API methods Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\", uri=\"/users\"}[$__rate_interval]))",
     "legendFormat": "Get users"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"POST\", uri=\"/users\"}[$__rate_interval]))",
     "legendFormat": "Post users"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\", uri=\"/users/{id}\"}[$__rate_interval]))",
     "legendFormat": "Get single user"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"PATCH\", uri=\"/users/{id}\"}[$__rate_interval]))",
     "legendFormat": "Edit user"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"DELETE\", uri=\"/users/{id}\"}[$__rate_interval]))",
     "legendFormat": "Delete user"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\", uri=\"/users\", status=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "Get users"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"POST\", uri=\"/users\", status=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "Post users"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\", uri=\"/users/{id}\", status=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "Get single user"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"PATCH\", uri=\"/users/{id}\", status=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "Edit user"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"DELETE\", uri=\"/users/{id}\", status=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "Delete user"
    }
   ]
  },
  { "title": "Ingress metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginx_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{code!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{code!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{code!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{code!~\"5.+\"}[$__rate_interval])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{code=~\"5.+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU and Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"user-crud-user-crud-chart-.*\", image!=\"\"}[10m])) by (pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"user-crud-user-crud-chart-.*\", container!=\"POD\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}