apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-crud-chart.fullname" . }}
  labels:
    {{- include "user-crud-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-crud-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-crud-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "user-crud-chart.configMap" . }}
                  key: MONGO_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "user-crud-chart.configMap" . }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-crud-chart.secret" . }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "user-crud-chart.secret" . }}
                  key: DB_PASSWORD
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000