{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-crud-chart.fullname" . }}
  labels:
    {{- include "user-crud-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "user-crud-chart.fullname" . }}
  selector:
    matchLabels:
      {{- include "user-crud-chart.labels" . | nindent 6 }}
  endpoints:
    - interval: 5s
      port: web
      path: /actuator/prometheus
{{- end }}