apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-crud-chart.fullname" . }}
  labels:
    {{- include "user-crud-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-crud-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000